#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# gunzip n0012_449-129.p3dfmt.gz
runApplication plot3dToFoam -noBlank arn_3zone_129.p3dfmt
cp 0/U.orig 0/U
runApplication autoPatch 30. -overwrite
runApplication createPatch  -overwrite
runApplication patchSummary

runApplication decomposePar

export OMPI_ALLOW_RUN_AS_ROOT=1 
export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1

runParallel potentialFoam
runParallel $(getApplication)
mv log.$(getApplication) log.$(getApplication).0

runApplication reconstructParMesh -constant
runApplication reconstructPar #-latestTime

runApplication $(getApplication) -postProcess -func wallShearStress #-latestTime
mv log.$(getApplication) log.$(getApplication).1

rm -rf VTK
runApplication foamToVTK #-latestTime



#------------------------------------------------------------------------------
