#!/bin/bash

./Allclean
./Generatemesh

for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15;
do
	nu=$(awk '{printf("%.5e",2^-(5+$1))}' <<< "$i");
	echo "Iteration $i ongoing... Viscosity at $nu";
	sed -i "s/nu              [^;]*/nu              $nu/" constant/transportProperties;
	let "startTime=4000*(i-1)";
	let "endTime  =4000*i";
	sed -i 's/startTime       [^;]*/startTime       '$startTime'/' system/controlDict;
	sed -i 's/endTime         [^;]*/endTime         '$endTime'/' system/controlDict;
	
	./Hotstart &> /dev/null;

	printf -v endDir "%d" "$endTime"
	if [[ ! -d "$endDir" ]]
	then
		echo "Calculations broke down...";
		break;
	fi
done
