#!/bin/sh
#cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

mesh_name=$(find . -regex "./plate\.msh")
runApplication gmshToFoam $mesh_name

awk -v RS="\0" -v ORS="" '{ gsub(/inlet\n    {\n        type            patch;\n        physicalType    patch;/, "inlet\n    {\n        type            patch;\n        physicalType    inlet;"); print }' constant/polyMesh/boundary > tmp
awk -v RS="\0" -v ORS="" '{ gsub(/symmetry_y\n    {\n        type            patch;\n        physicalType    patch;/, "symmetry_y\n    {\n        type            symmetryPlane;\n        physicalType    symmetryPlane;\n        inGroups        1(symmetryPlane);"); print }' tmp > constant/polyMesh/boundary
awk -v RS="\0" -v ORS="" '{ gsub(/symmetry_z\n    {\n        type            patch;\n        physicalType    patch;/, "symmetry_z\n    {\n        type            symmetryPlane;\n        physicalType    symmetryPlane;\n        inGroups        1(symmetryPlane);"); print }' constant/polyMesh/boundary > tmp
awk -v RS="\0" -v ORS="" '{ gsub(/infinity_x\n    {\n        type            patch;\n        physicalType    patch;/, "infinity_x\n    {\n        type            patch;\n        physicalType    outlet;\n        inGroups        1(outlet);"); print }' tmp > constant/polyMesh/boundary
awk -v RS="\0" -v ORS="" '{ gsub(/infinity_y\n    {\n        type            patch;\n        physicalType    patch;/, "infinity_y\n    {\n        type            patch;\n        physicalType    outlet;\n        inGroups        1(outlet);"); print }' constant/polyMesh/boundary > tmp
awk -v RS="\0" -v ORS="" '{ gsub(/infinity_z\n    {\n        type            patch;\n        physicalType    patch;/, "infinity_z\n    {\n        type            patch;\n        physicalType    outlet;\n        inGroups        1(outlet);"); print }' tmp > constant/polyMesh/boundary
awk -v RS="\0" -v ORS="" '{ gsub(/wall\n    {\n        type            patch;\n        physicalType    patch;/, "wall\n    {\n        type            wall;\n        physicalType    wall;"); print }' constant/polyMesh/boundary > tmp
mv tmp constant/polyMesh/boundary

cp -r 0.orig 0

