#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication decomposePar

export OMPI_ALLOW_RUN_AS_ROOT=1 
export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1

# Solver choice
runParallel simpleFoam

runApplication reconstructParMesh -constant
runApplication reconstructPar -latestTime

runParallel foamToVTK -fields '(p U nut)' -patches '(front)' -no-internal -latestTime -overwrite 

#------------------------------------------------------------------------------
