#!/bin/bash

./Allclean
./Generatemesh

sed -i 's/tolerance       [^;]*/tolerance       1e-6/' system/fvSolution;
sed -i 's/p       [^;]*/p       1e-4/' system/fvSolution;
sed -i 's/U       [^;]*/U       1e-6/' system/fvSolution;
sed -i 's/nuTilda [^;]*/nuTilda 1e-5/' system/fvSolution;
sed -i '53s/U     [^;]*/U     .99/' system/fvSolution;
sed -i '54s/".*"  [^;]*/".*"  .99/' system/fvSolution;
sed -i 's/writeInterval     [^;]*/writeInterval     $endTime/' system/controlDict;

for i in 1 2 3; do
	nu=$(awk '{printf("%.5e",10^ -(2+$1))}' <<< "$i");
	echo "Iteration $i ongoing... Viscosity at $nu";
	sed -i "s/nu              [^;]*/nu              $nu/" constant/transportProperties;
	let "startTime=0";
	if [[  "$i" -gt 0 ]]; then
		l=$(find . -type d -regex "./[0-9]*");
		for x in $l ; do
   			n=${x#\.\/}; # take just the number so that comparisons work 
    			[ "$n" -gt "$startTime" ] && startTime=$n; 
  		done
	fi
	let "endTime=startTime+1000";
	sed -i 's/startTime         [^;]*/startTime         '$startTime'/' system/controlDict;
	sed -i 's/endTime           [^;]*/endTime           '$endTime'/' system/controlDict;
	
	./Hotstart &> /dev/null;

	if ! tail -1 log.simpleFoam | grep "Finalising parallel run"; then
		echo "UNEXPECTED ERROR ! Calculations broke down...";
		break;
	fi
done

# Final increment in viscosity
sed -i 's/nu              [^;]*/nu              5.e-6/' constant/transportProperties;
sed -i 's/startTime         [^;]*/startTime         '$endTime'/' system/controlDict;	
let "endTime=endTime+2000";
sed -i 's/endTime           [^;]*/endTime           '$endTime'/' system/controlDict;
echo "Final iteration ongoing... Viscosity at 5.e-6 !";

./Hotstart &> /dev/null;

if ! tail -1 log.simpleFoam | grep "Finalising parallel run"; then
	echo "UNEXPECTED ERROR ! Calculations broke down...";
	exit 0;
fi

# Increasing swirl
sed -i '53s/U     [^;]*/U     .9/' system/fvSolution;
sed -i '54s/".*"  [^;]*/".*"  .9/' system/fvSolution;
sed -i 's/startTime         [^;]*/startTime         '$endTime'/' system/controlDict;	
let "endTime=endTime+5000*16";
sed -i 's/endTime           [^;]*/endTime           '$endTime'/' system/controlDict;
sed -i 's/writeInterval     [^;]*/writeInterval     5000/' system/controlDict;
echo "Increasing swirl...";

./Hotstart &> /dev/null;

if ! tail -1 log.simpleFoam | grep "Finalising parallel run"; then
	echo "UNEXPECTED ERROR ! Calculations broke down...";
fi
